# policy_path: {LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250523_194729-MotionTracking_CR7-motion_tracking-g1_29dof_anneal_23dof/exported/model_8000.pt" 
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250526_114429-MotionTracking_Stand-motion_tracking-g1_29dof_anneal_23dof/exported/model_5000.pt"
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250529_214230-MotionTracking_TStand-motion_tracking-g1_29dof_anneal_23dof/exported/model_5000.pt"
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250530_235025-MotionTracking_TStand-motion_tracking-g1_29dof_anneal_23dof/exported/model_5000.pt"
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250530_235101-MotionTracking_TStand-motion_tracking-g1_29dof_anneal_23dof/exported/model_5000.pt"
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250601_221200-MotionTracking_TStand-motion_tracking-g1_29dof_anneal_23dof/exported/model_13000.pt"
# policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250601_222051-MotionTracking_TStand-motion_tracking-g1_29dof_anneal_23dof/exported/model_13000.pt"
policy_path: "/media/hanx/Ventoy/Uproject/ASAP-main/logs/MotionTracking/20250602_133458-MotionTracking_TStand-motion_tracking-g1_29dof_anneal_23dof/exported/model_1000.pt"
# policy_path: "deploy/pre_train/g1/motion.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene.xml"
# xml_path: "/media/hanx/Ventoy/Uproject/ASAP-main/humanoidverse/data/robots/g1/g1_29dof_anneal_23dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002 #0.05
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 2 #4 

# kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
# kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]
kps: [100, 100, 100, 200, 20, 20,
      100, 100, 100, 200, 20, 20,
      400, 400, 400,
      90, 60, 20, 60,
      90, 60, 20, 60]

kds: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
      2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
      5.0, 5.0, 5.0,
      2.0, 1.0, 0.4, 1.0,
      2.0, 1.0, 0.4, 1.0]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                  0.0, 0.0, 0.0, 0.0, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 23 #12
num_obs: 75

cmd_init: [0.5, 0, 0]

# === ASAP/IsaacGym对齐的clip参数 ===
action_clip_value: 100.0         # 通常为1.0，需与训练时一致
clip_torques: true             # 是否对力矩clip
torque_limits: [
      88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
      88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
      88.0, 50.0, 50.0,
      25.0, 25.0, 25.0, 25.0, 
      25.0, 25.0, 25.0, 25.0
      ]